// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFinanceiroMonitor.Infrastructure.Data.Context;

#nullable disable

namespace SistemaFinanceiroMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212174132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoDisparo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PercentualGatilho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoAlerta")
                        .HasColumnType("int");

                    b.Property<int?>("TipoIndicador")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMoeda")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorGatilho")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCotacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoMoeda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoMoeda", "DataCotacao");

                    b.ToTable("Cotacoes", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.HistoricoAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDisparo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEnvioEmail")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorNoMomento")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.ToTable("HistoricoAlertas", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.IndicadorEconomico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoIndicador")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("TipoIndicador", "DataReferencia");

                    b.ToTable("Indicadores", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("SistemaFinanceiroMonitor.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Cotacao", b =>
                {
                    b.OwnsOne("SistemaFinanceiroMonitor.Domain.ValueObjects.ValorMonetario", "ValorCompra", b1 =>
                        {
                            b1.Property<int>("CotacaoId")
                                .HasColumnType("int");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MoedaCompra");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("ValorCompra");

                            b1.HasKey("CotacaoId");

                            b1.ToTable("Cotacoes");

                            b1.WithOwner()
                                .HasForeignKey("CotacaoId");
                        });

                    b.OwnsOne("SistemaFinanceiroMonitor.Domain.ValueObjects.ValorMonetario", "ValorVenda", b1 =>
                        {
                            b1.Property<int>("CotacaoId")
                                .HasColumnType("int");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MoedaVenda");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("ValorVenda");

                            b1.HasKey("CotacaoId");

                            b1.ToTable("Cotacoes");

                            b1.WithOwner()
                                .HasForeignKey("CotacaoId");
                        });

                    b.Navigation("ValorCompra")
                        .IsRequired();

                    b.Navigation("ValorVenda")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.HistoricoAlerta", b =>
                {
                    b.HasOne("SistemaFinanceiroMonitor.Domain.Entities.Alerta", "Alerta")
                        .WithMany("Historico")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("SistemaFinanceiroMonitor.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Endereco")
                                .IsUnique()
                                .HasDatabaseName("IX_Usuarios_Email");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Alerta", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("SistemaFinanceiroMonitor.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
